title: Edwin Mathew
logo: ./assets/img/DP.png
description: <a href="https://www.linkedin.com/in/edwin-mathew0012"><img src="./assets/img/linkedin.png" width='100' style='padding-left:85px'></a>
github:
  is_project_page: false
theme: jekyll-theme-minimal
sass:
  sass_dir: _assets
